import type { Metadata } from "next";
// import {Geist, Geist_Mono} from "next/font/google";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Footer from "@/Components/Footer";
import { getFooterData, getHeaderData, siteSettingsData } from "@/sanity/lib/api";
import Script from "next/script";


const pageData = await siteSettingsData();
const footerData = await getFooterData();
const headerData = await getHeaderData();

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'], // Add the weights you use
    variable: '--font-poppins', // Optional: CSS variable name
});
// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <title>{pageData?.siteName}</title>
                <script>{`window.__HEADER_DATA__ = ${JSON.stringify(headerData?.header_scripts)}`}</script>
            </head>
            <body
                className={`${poppins.variable}`}
            >
                {/*<Navbar/>*/}
                {children}
                <Footer />
                <script>{`window.__PAGE_DATA__ = ${JSON.stringify(pageData?.script)}`}</script>
                <script>{`window.__FOOTER_DATA__ = ${JSON.stringify(footerData?.footerScripts)}`}</script>
                <Script
                    id="linkedin-insight-tag"
                    strategy="lazyOnload"
                    dangerouslySetInnerHTML={{
                        __html: `
            _linkedin_partner_id = "7564164";
            window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
            window._linkedin_data_partner_ids.push(_linkedin_partner_id);
            (function(l) {
              if (!l) {
                window.lintrk = function(a,b) { window.lintrk.q.push([a,b]) };
                window.lintrk.q = [];
              }
              var s = document.getElementsByTagName("script")[0];
              var b = document.createElement("script");
              b.type = "text/javascript";
              b.async = true;
              b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
              s.parentNode.insertBefore(b, s);
            })(window.lintrk);
          `,
                    }}
                />
                <noscript>
                    <img
                        height="1"
                        width="1"
                        style={{ display: 'none' }}
                        alt=""
                        src="https://px.ads.linkedin.com/collect/?pid=7564164&fmt=gif"
                    />
                </noscript>
            </body>
        </html>
        
    );


}



